Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bearer.Models;
using ModelsClassLibrary.Models.CountryNS;
using Bearer.DAL;
using System.Text;
using ModelsClassLibrary.Models.AddressNS;

namespace Bearer.Controllers
{
    public class AddressesController : AbstractController<Address>
    {

        private static ApplicationDbContext _db;
        private static string _user;
        
        
        //public  LanguageDAL lDal;
        public AddressesController()
            : base(new AddressDAL(SetApplicationDbContext(), GetUser()))
        {

        }


        private static ApplicationDbContext SetApplicationDbContext()
        {
            _db = new ApplicationDbContext();
            return _db;
        }

        private static string GetUser()
        {
            StringBuilder sb = new StringBuilder();
            string s = AliKuli.GetSet.Name(null);
            sb.Append(s);
            _user = s.ToString();
            return _user;
        }


        //====================================================================


        

        public override ActionResult Create()
        {
            CountryDAL cDal = new CountryDAL(_db, _user);
            ViewBag.Countries = cDal.SelectList();

            return base.Create();
        }






        public override async Task<ActionResult> Edit([Bind(Include = "Id,Name,Comment,ModifiedDateStart,PhoneIntlCode,Abbreviation,HouseNo,Road,Address2,City,State,Zip,CountryID")] Address entity)
        {
            CountryDAL cDal = new CountryDAL(_db, _user);
            ViewBag.Countries = cDal.SelectList();

            return await base.Edit(entity);
        }

        public override async Task<ActionResult> Edit(long? id)
        {
            CountryDAL cDal = new CountryDAL(_db, _user);
            ViewBag.Countries = cDal.SelectList();

            return await base.Edit(id);
        }

    }
}

Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bearer.Models;
using ModelsClassLibrary.Models.CountryNS;
using Bearer.DAL;
using System.Text;

namespace Bearer.Controllers
{
    public class CountriesController : AbstractController<Country>
    {
        //public  LanguageDAL lDal;
        public CountriesController()
            : base(new CountryDAL(SetApplicationDbContext(), GetUser()))
        {

        }


        //private static LanguageDAL SetLanguageDal()
        //{
        //    lDal = ;
        //    return lDal;

        //}

        private static ApplicationDbContext SetApplicationDbContext()
        {
            return new ApplicationDbContext();
        }

        private static string GetUser()
        {
            StringBuilder sb = new StringBuilder();
            string s = AliKuli.GetSet.Name(null);
            sb.Append(s);
            return s.ToString();
        }

        public override async Task<ActionResult> Index(string message = "")
        {
            if (!string.IsNullOrEmpty(message))
            {
                ModelState.AddModelError("", message);
            }

            try
            {
                var t = await repo.FindAllAsync();
                return View(t.OrderBy(x => x.Name));

            }
            catch (Exception e)
            {
                MakeErrorMesage("Something went wrong. Try again.", e);
                return View(repo.FindAll().OrderBy(x => x.Name));
            }

        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bearer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

Controllers/PeopleController.cs
using Bearer.DAL;
using Bearer.Models;
using ModelsClassLibrary.Models.AddressNS;
using ModelsClassLibrary.Models.People;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AliKuli.Extentions;

namespace Bearer.Controllers
{
    public class PeopleController:AbstractController<Person>
    {
        public PeopleController()
            : base(new PersonDAL(SetApplicationDbContext(), GetUser()))
        {

        }

        private static ApplicationDbContext SetApplicationDbContext()
        {
            return new ApplicationDbContext();
        }

        private static string GetUser()
        {
            StringBuilder sb = new StringBuilder();
            string s = AliKuli.GetSet.Name(null);
            sb.Append(s);
            return s.ToString();
        }

        public override async Task<ActionResult> Index(string message = "")
        {
            //We need the select list from Address
            Repositry<Address> addressRep = new AddressDAL(base.repo.GetDb, base.repo.GetUser);
            AddressDAL addyDAL = (AddressDAL)addressRep;
            //ViewBag.AddressSelectList = addyDAL.SelectList();

            ViewBag.AddressSelectList = addyDAL.SelectList();
            return await base.Index(message);
        }   
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>This program is designed to help maintain and view Customers and their IP addresses. This is just a simple program on which a proper solution can be built.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>For Help... Contact</h2>
<h3>@ViewBag.Message</h3>

<address>
    Ali Kuli Aminuddin<br />
    Gulkali, Main Harbanspura<br />
    Lahore, Pakistan<br />
    <abbr title="Phone">P:</abbr>
    0331.447.4120
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:alikuli62@gmail.com">alikuli62@gmai.com</a><br />
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron text-center">
    <h1>@AliKuli.Misc.WebRequests.CompanyName</h1>
    <p>Bearer Solution</p>
</div>

<div class="container">
    <div class="row text-center">
        <h1>Menu</h1>  
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-2">
        <div><h2>Menu 1</h2></div>
        <div class="row">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Person", "Index", "People")</li>
                <li>@Html.ActionLink("Languages", "Index", "Languages")</li>
                <li>@Html.ActionLink("PersonLang", "Index", "PersonLanguages")</li>
                <li>@Html.ActionLink("Country", "Index", "Countries")</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-2">
        <div> <h2>Menu 2</h2></div>
        @{
            <ul>
                <li>@Html.ActionLink("Address", "Index", "Addresses")</li>
                @*//if (User.IsInRole(AliKuli.MyConstants.AdminConst))*@
                @*@if (User.IsInRole("Administrator"))*@
                @if (User.IsInRole(AliKuli.MyConstants.AdminConst))
                {

                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Setup", "Index", "Setups")</li>
                }
            </ul>
        }

    </div>
    <div class="col-lg-2">
        <div> <h2>Menu 3</h2></div>
        @{
            <ul>
                <li>Test</li>
                <li>Test</li>
                <li>Test</li>
                @*//if (User.IsInRole(AliKuli.MyConstants.AdminConst))*@
                @*@if (User.IsInRole("Administrator"))*@
                @if (User.IsInRole(AliKuli.MyConstants.AdminConst))
                {

                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Setup", "Index", "Setups")</li>
                }
            </ul>
        }

    </div>


    <div class="col-lg-2">
        <div> <h2>Menu 4</h2></div>
        @{
            <ul>
                <li>Test</li>
                <li>Test</li>
                <li>Test</li>
                @*//if (User.IsInRole(AliKuli.MyConstants.AdminConst))*@
                @*@if (User.IsInRole("Administrator"))*@
                @if (User.IsInRole(AliKuli.MyConstants.AdminConst))
                {

                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Setup", "Index", "Setups")</li>
                }
            </ul>
        }

    </div>

    <div class="col-lg-2">
        <div> <h2>Menu 5</h2></div>
        @{
            <ul>
                <li>Test</li>
                <li>Test</li>
                <li>Test</li>
                @*//if (User.IsInRole(AliKuli.MyConstants.AdminConst))*@
                @*@if (User.IsInRole("Administrator"))*@
                @if (User.IsInRole(AliKuli.MyConstants.AdminConst))
                {

                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Setup", "Index", "Setups")</li>
                }
            </ul>
        }

    </div>

    <div class="col-lg-2">
        <div> <h2>Menu 6</h2></div>
        @{
            <ul>
                <li>Test</li>
                <li>Test</li>
                <li>Test</li>
                @*//if (User.IsInRole(AliKuli.MyConstants.AdminConst))*@
                @*@if (User.IsInRole("Administrator"))*@
                @if (User.IsInRole(AliKuli.MyConstants.AdminConst))
                {

                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Setup", "Index", "Setups")</li>
                }
            </ul>
        }

    </div>

</div>